### ISSUE TITLE
Add a namespace to all classes

### ISSUE THREAD

**Issue by comio** [erezgeva/libpmc#1]
Hi erezgeva,

I'm following your work on this library. This is not a real issue of course.

can you add a namespace like "libpmc"?

ciao

luigi

**Comment by erezgeva** [comment]
I an novice on that,
Could you point me to instructions.

Thanks for the tip :-)

**Comment by erezgeva** [comment]
Do you mean C++ namespace for.

Most scripts do a "namespace" by default.
As interfaces can be access through the packages import.

As for C++, a namespace might be a good idea.
I can try.
But I do not promise.
I need to see how to pull it out.

Erez

**Comment by erezgeva** [comment]
As most script languages already use name space.
And as using C++ name space seems to break some script languages,
I decided to leave library as is.
