### ISSUE TITLE
How to set bitmask of SUBSCRIBE_EVENTS_NP_t?

### ISSUE THREAD

**Issue by peci1** [erezgeva/libpmc#3]
It seems the bitmask is either missing add/clear flag methods, or is missing a converter to some native type.

In Python, I currently use this to change the value:

```python
bitmask = s.bitmask
bitmask_data = ctypes.cast(bitmask.__long__(), ctypes.POINTER(ctypes.c_uint8))
bitmask_data[0] = 0 | (1 << pmc.NOTIFY_PORT_STATE) | (1 << pmc.NOTIFY_TIME_SYNC)
for i in range(1, pmc.EVENT_BITMASK_CNT):
    bitmask_data[i] = 0
```

I think it would be better to expose the `EVENT_BIT_SET` and `EVENT_BIT_CLEAR` macros as interface functions.

**Comment by erezgeva** [comment]
Good point.
I have macros in C++ but no proper functions for swig.
I convert the macros to functions of SUBSCRIBE_EVENTS_NP_t itself -:)

**Comment by erezgeva** [comment]
As for `EVENT_BIT_SET` and `EVENT_BIT_CLEAR` 
I define them in C++ not in Python. I let swig do the translation.
This is how we get so many scripts languages supported.
The code might looks sometimes less pretty, but in the overall, the performance is high.
And the syntax is reasonable.
Anyway, you are welcome to pull request.
If the code is proper, I'll merge.
As for using the new events access functions,
 See [python/test.py](https://github.com/erezgeva/libpmc/blob/master/python/test.py)  for example of setting event in `SUBSCRIBE_EVENTS_NP_t` and read it.
